[features]
seeds = false
skip-lint = false
[programs.localnet]
versioning = "8EEY7nX8xNTgNHvsYAhKZ8TwLP6eJLEhBZGbJWx3vtD6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/jack/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
